### PR TITLE
AaiServers and SecuritySchemes part 2

### PR DESCRIPTION
**Pull request by DyspC**
Hi,

This PR follows https://github.com/Apicurio/apicurio-data-models/pull/252 with some ajustments around SecurityRequirements alongside some fixes.

The notable change is AaiServer joining OasDocument / OasOperation under the ISecurityRequirementParent interface since both specifications store them the same way (a list)

I should be able to send the teased studio part soon as well.

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]
Nice changes thanks!

**Comment by DyspC** [comment]
Hi @EricWittmann,
 
Sorry I was a bit busy this week and just remembered I skipped a todo in my studio files about a missing comfort command to avoid having to click 'Undo' 2 times after clearing a channel from its operations. (DeleteAllOperationsCommand_Aai20 or along those lines, the logic looks about the same)
Perhaps you'd like to wrap it before the next release or it can wait until I find more things to add in another PR.

--
The todo culprit from channel/operations-section
```java
    public deleteAllOperations(): void {
        //let command: ICommand = CommandFactory.createDeleteAllOperationsCommand(this.path);
        //this.commandService.emit(command);
        for (let operation of this.channelOperations()) { // FIXME use an atomic command from datamodels
            this.deleteOperation(operation);
        }
    }
```

**Comment by EricWittmann** [comment]
Releases are cheap in this library.  I'm happy to cut a release (do you need one now?) or wait for you to add more features.  :)  Whatever works for you.

Also note:  there is a way to aggregate commands into a single command.  You could try that as a short-term fix.  I think the DeleteAllOperations command would probably be nicer, but obviously more work.

https://github.com/Apicurio/apicurio-data-models/blob/master/src/main/java/io/apicurio/datamodels/cmd/commands/AggregateCommand.java

**Comment by DyspC** [comment]
Hi, 

The AggregateCommand is nice to know thanks, I had a bit of time today and sent a quick PR with the DeleteAllOperations_Aai20 but I should remember this one.

We're currently busy preparing our production environment so there's no need for it to be quick but since I prefer deploying my studio branches on staging envs before sending the PR, the sooner the lib gets released the sooner I can test and finalize it.

**Pull request merged**
