### PR TITLE
Add DeleteAllOperationsCommand_Aai20 Command

### PR DESCRIPTION
**Pull request by DyspC**
Hello, 

This PR adds the command I [forgot to implement in my last one](https://github.com/Apicurio/apicurio-data-models/pull/265#issuecomment-833667247), sorry for the double.

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Builds are failing I think due to some changes in the latest version of maven.  I'm working on trying to fix it.

**Comment by DyspC** [comment]
> The only solution I can think of right now is to create my own docker image to run the build on. I don't really have the time for that this week.

I don't know about github actions but I'm using [maven:3.6.3-openjdk-11](https://hub.docker.com/layers/maven/library/maven/3.6.3-openjdk-11/images/sha256-1801d353e27e68d60355b371ddfd2ed8d06204bc3266f1746fdade897bb8b6bd?context=explore) in gitlab-ci to build the studio

**Comment by riprasad** [comment]
@EricWittmann I initially tried building with different combinations of maven versions using maven wrappers but failed every time. So I took the alternative approach of building inside the docker images. 

I initially used the docker image [maven:3.6.3-openjdk-11](https://hub.docker.com/layers/maven/library/maven/3.6.3-openjdk-11/images/sha256-1801d353e27e68d60355b371ddfd2ed8d06204bc3266f1746fdade897bb8b6bd?context=explore) since @DyspC  uses that in GitLab CI to build studio. Not sure how it's working for him, but It's failing for me as Jsweet is not compatible with jdk-11.

I then moved on to use [3.6.3-openjdk-8](https://hub.docker.com/layers/maven/library/maven/3.6.3-openjdk-8/images/sha256-09c4bf58d7e7e31bdc1ab73ef10349b3a47c9a814e715e409034fb3293253ce2?context=explore), but it failed again since it was looking for node.js
```
2021-05-12 10:58:11.011 ERROR output:55 - cannot find Node.js: install first and make sure that the 'node' command is in your execution path
2021-05-12 10:58:11.011 ERROR JSweetTranspiler:816 - cannot find node.js
```

Finally, I used an image that packs node along with jdk 8 and maven i.e. [docker-jdk-8-maven-node](https://hub.docker.com/r/jimador/docker-jdk-8-maven-node/) and the build was successful. However, I fail to understand why studio needs node for building now but it was building successfully without it in the past.

**Comment by EricWittmann** [comment]
Oh - the answer is that this repository is `apicurio-data-models` not `apicurio-studio`.  This is just the data model library that is the basis for some of the Studio functionality.  This library uses a tool called JSweet to transpile Java source code into Typescript.  It then builds the resulting typescript code into a standard NPM (and browser) module.

Apparently the JSweet plugin requires node.js to do its thing.

**Comment by riprasad** [comment]
> Oh - the answer is that this repository is `apicurio-data-models` not `apicurio-studio`. 
Ah! of course. my bad. 

Also, I forgot the fact that action runners have node pre-installed.

**Comment by EricWittmann** [comment]
No worries.  I actually didn't know that JSweet required node.js to be installed.  Apparently I just **happen** to have node.js installed everywhere that I've ever tried to build apicurio-data-models!  :)

**Comment by EricWittmann** [comment]
@DyspC FYI I have released version 1.1.11 of the data-models library.  Sorry for the delay, this was unfortunately a bit down on the ol' priority list.  But it's done now and can be used in Studio!  :)

**Comment by DyspC** [comment]
Alright tyvm

**Comment by DyspC** [comment]
Hi @EricWittmann,

The maven release of 1.1.11 appears to have failed 

The deploy script looks like it won't do retries because the sleep command rarely fails (adding `&& false` after the sleep would be a quick fix)
https://github.com/Apicurio/apicurio-data-models/runs/2642120857?check_suite_focus=true#step:22:4

**Comment by EricWittmann** [comment]
Darn it.  I had a lot of trouble with the release workflow I need to figure out.  I'll try to do the maven deploy manually and let you know here when it's done.

**Comment by EricWittmann** [comment]
OK @DyspC I think we should be good now.  Manual release seems to have done the trick.

**Pull request merged**
