### PR TITLE
Feat/headers

### PR DESCRIPTION
**Pull request by vvilerio**
Hi,
When running the tests the _newHeader field from commands.json is deserialized to LinkedHashMap instead of JsonNode and causes an exception in Library.readNode. 

@EricWittmann  : Did I make a mistake somewhere?

```
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.fasterxml.jackson.databind.JsonNode (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.JsonNode is in unnamed module of loader 'app')

```

cf: https://github.com/Apicurio/apicurio-studio/issues/1411

### CODE REVIEW

**Comment by EricWittmann** [comment]
Hi @vvilerio sorry for the delay.  I'm WAY behind on my github notifications.  I'll take a look now.

**Comment by vvilerio** [comment]
Thank you very much for your answers.
I will look into it right away.

**Comment by EricWittmann** [comment]
Given that I made you wait almost a week for any feedback, take your time!!  :) :)

**Comment by vvilerio** [comment]
@EricWittmann : Hello, I have a little problem with the creation of my new ChangeHeaderTypeCommand which is based on the ChangeMediaTypeCommand template.

If I use it in my local apicurio-studio after using the :
`mvn clean install -Ptranspilation -DskipTests`

everything seems to work fine, but if I run the transpilation without the `-DskipTests` then I get an error. 

> ChangeHeaderTypeCommand] _headerPath is /paths[/foo]/get/responses[200]/headers[X-RateLimit-Remaining] and of type function String() { [native code] }.
> 
> whereas for ChangeMediaTypeCommand
> ChangeMediaTypeCommand] _mediaTypePath is /paths[/foo]/get/responses[200]/content[application/json] and of type function NodePath(path)

Do you have an idea about this problem?

Translated with www.DeepL.com/Translator (free version)

**Comment by vvilerio** [comment]
Hi, 
I'm taking the liberty of bringing up this conversation because the PR about the UI is waiting in the background.

Sorry to be a bit insistent.

**Comment by EricWittmann** [comment]
OK I'll look at this today, sorry for making you wait.

**Comment by EricWittmann** [comment]
I've replicated the error.  No idea yet what's going on. :)  Also no need to apologize for being insistent.  If you aren't then I can easily forget about an issue and it will slip through the cracks.

**Comment by EricWittmann** [comment]
So this was tricky and very understandable that you were asking yourself "wtf is going on"?  The problem is in the command marshaller, which is responsible for converting a command into a JSON document for persistence and exchange purposes.  Marshalling doesn't work automatically in typescript for command fields of type `NodePath` (but it **does** work automatically in Java).

What you need to do is add `_headerPath` as an option here:

https://github.com/Apicurio/apicurio-data-models/blob/master/src/main/ts/src/io/apicurio/datamodels/compat/MarshallCompat.ts#L23-L26

Just add that to the list of field names.

**Comment by EricWittmann** [comment]
By the way - there is another test failure.  This file is not a valid JSON file:  `src\test\resources\fixtures\cmd\commands\change-header\openapi-3\change-header-response.after.json` 

It just has an extra bit of content at the end of the file... just a copy/paste artifact probably.  Remove it and you should be good.

**Comment by EricWittmann** [comment]
Thank you for the contribution!!

**Comment by EricWittmann** [comment]
I will kick off a new release.

**Comment by EricWittmann** [comment]
Release is done!

**Pull request merged**
