### PR TITLE
Asyncapi 20 commands round 2

### PR DESCRIPTION
**Pull request by lbroudoux**
Adding some more commands that are necessary for manipulation an Async API document from Studio.
Merge will also require a new release in order to integrate those changes into Apicurio Studio.

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]
Awesome thanks!

**Comment by lbroudoux** [comment]
Thanks for the merge @EricWittmann!
Could also make the release so that I can create another PR on the Apicurio Studio side?

Many thanks!

**Comment by EricWittmann** [comment]
Yes, but I was hoping to get some updated AsyncAPI validation work checked in before the release.  But it's still incomplete, so I'll just go ahead with a new release since they are cheap.  :)

**Comment by EricWittmann** [comment]
In progress.   Give it 30 minutes and it should be done.  I'll try to remember to check back to make sure it worked, but I have some meetings today and will be distracted as a result. :)

**Comment by EricWittmann** [comment]
Looks like it worked. :)

https://github.com/Apicurio/apicurio-data-models/releases/tag/1.1.6

**Pull request merged**
