### PR TITLE
Fix for message payload ref command.  Added test for changing a message ref

### PR DESCRIPTION
**Pull request by EricWittmann**
What I've done here is fixed the `ChangePayloadRefCommand_Aai20` class to accept an `AaiMessage` rather than an `AaiOperation`.  That will make it more generic in its usefulness I think.  So it will work with message components as well as those that are inline in operations.  I've left the old behavior but deprecated it.

Next, in response to https://github.com/Apicurio/apicurio-data-models/pull/364 where there is a proposal to add an operation to change a reference in a oneOf of a message (see that PR).  Instead I think that use-case is covered by the standard/existing `ChangePropertyCommand`.  Since a `$ref` is just a simple property, I think we don't need a separate operation to change or set it.

### CODE REVIEW

**Review by vvilerio — APPROVED** [review]
well, it's more precise and efficient, thanks.

**Comment by EricWittmann** [comment]
Yes unfortunately changing `$ref` for a payload needs to be a special case for the reason you give.  But for the `oneOf` case I think it should work fine.  I'll assume it's OK and we can address it in a followup if I'm wrong. :)

**Comment by EricWittmann** [comment]
@vvilerio I'm releasing data-models 1.1.20 now - if all goes well we can upgrade studio and we can get your other PR finished. :)  As always thanks for your contributions!

**Comment by EricWittmann** [comment]
Done!

**Pull request merged**
