### PR TITLE
bugfix : Fix the problem of payload management in messages from the m…

### PR DESCRIPTION
**Pull request by vvilerio**
bugfix : Fix the problem of payload management in messages from the messages section (was working from the operations section) and adding change/update reference in messages(oneOf) from an operatio
MessageOneOfPbm

updateMessageOneOf
n

### CODE REVIEW

**Comment by vvilerio** [comment]
@EricWittmann -- And the White Rabbit says "I'm late, I'm late! For a very important date! No time to say commit, push, and Merge" :
no-time
)

**Comment by EricWittmann** [comment]
Hey @vvilerio .  After reviewing this PR I think there may be better ways to do both of these things.  It seemed faster to just do them rather than write it up here in a response to this PR.  So could you please review this PR?

https://github.com/Apicurio/apicurio-data-models/pull/371

I've added some explanation in the description of that PR.  Please let me know what you think!

**Comment by EricWittmann** [comment]
Also note that as part of that PR I have actually used your exact test (just relocated) to make sure that the use-case is hopefully covered.  However, I could easily be missing something.

**Comment by EricWittmann** [comment]
This was implemented slightly differently in https://github.com/Apicurio/apicurio-data-models/pull/371

**Comment by vvilerio** [comment]
Thanks and Best whishing to you

**Comment by EricWittmann** [comment]
Happy New Year!  :)

**Pull request closed without merging**
